# ^T (Ctrl-T) を prefix に設定
unbind C-b
set-option -g prefix C-t
bind-key C-t send-prefix
set -g mouse on
set -g focus-events on

set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'dracula/tmux'
run '~/.tmux/plugins/tpm/tpm'
